variable "name"               { type = string }
variable "vpc_id"             { type = string }
variable "private_db_subnets" { type = list(string) }
variable "db_engine"          { type = string }
variable "db_engine_version"  { type = string }
variable "instance_class"     { type = string }
variable "db_username"        { type = string }
variable "db_password"        { type = string }
variable "db_sg_source_id"    { type = string } # app SG id to allow from
