name: Build & Push Images
on:
  push:
    branches: ["main"]
    paths: ["app/**"]
permissions:
  id-token: write
  contents: read
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ap-south-1
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push
        env:
          ECR_FE: ${{ vars.ECR_REPO_FRONTEND }}
          ECR_BE: ${{ vars.ECR_REPO_BACKEND }}
          COMMIT: ${{ github.sha }}
        run: |
          docker build -t $ECR_FE:latest -t $ECR_FE:$COMMIT ./app/frontend
          docker push $ECR_FE --all-tags
          docker build -t $ECR_BE:latest -t $ECR_BE:$COMMIT ./app/backend
          docker push $ECR_BE --all-tags
