name: Terraform Apply
on:
  push:
    branches: ["main"]
    paths: ["Terraform/**"]
permissions:
  id-token: write
  contents: read
jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Apply
        working-directory: infra
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false -var-file=envs/dev/terraform.tfvars
