name: Terraform CI
on:
  pull_request:
    paths: ["infra/**"]
permissions:
  id-token: write
  contents: read
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ap-south-1
      - name: Fmt/Validate/Plan
        working-directory: infra
        run: |
          terraform fmt -check
          terraform init -input=false
          terraform validate
          terraform plan -input=false -var-file=envs/dev/terraform.tfvars -no-color
