name: Terraform Apply

on:
  push:
    branches: ["main"]
    paths: ["Terraform/**"]

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod

    defaults:
      run:
        working-directory: Terraform   # sets working directory for all Terraform steps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Init
        run: terraform init -input=false -backend-config=envs/dev/backend.hcl


      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var-file=envs/dev/terraform.tfvars
